name: Docker Build & Push

on:
  pull_request:
    types:
      - closed
    branches:
      - desarrollo
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t dockerbruhh/pruscii:latest .
      
    - name: Log in to Docker Hub
      run: docker login -u dockerbruhh -p ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push Docker image
      run: docker push dockerbruhh/pruscii:latest
